#cloud-config
packages:
  - unzip
  - curl

%{ if extra_runcmd != "" }
runcmd:
  - curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
  - unzip /tmp/awscliv2.zip -d /tmp
  - /tmp/aws/install
  - ${extra_runcmd}
%{ else }
runcmd:
  - curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
  - unzip /tmp/awscliv2.zip -d /tmp
  - /tmp/aws/install
%{ endif }
