#This workflow runs on push to main and opens a release PR based on conventional commits.
name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release with Conventional Commits
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: terraform-module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
