name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release with Conventional Commits
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: terraform-module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip Terraform module
        if: steps.release.outputs.release_created == 'true'
        run: |
          mkdir module
          cp -r *.tf *.md cloud_init.tmpl.yaml module/ 2>/dev/null || true
          zip -r terraform-module.zip module

      - name: Upload release artifact
        if: steps.release.outputs.release_created == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: terraform-module.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
